# Purpose: Creates the container for running the uMetadata software.
# Usage: podman build -t umetadata:latest -f Dockerfile.deb
#        buildah bud -t umetadata:latest -f Dockerfile.deb
FROM debian:bookworm-slim
ADD uMetadata-@PROJECT_VERSION@-Linux.deb .
RUN apt-get update &&\
    apt-get upgrade -y &&\
    apt-get autoremove -y &&\
    apt-get autoclean -y &&\
    apt-get -y install bash &&\
    apt-get -y --no-install-recommends install ./uMetadata-@PROJECT_VERSION@-Linux.deb &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    rm -r /var/lib/apt/lists/* uMetadata-@PROJECT_VERSION@-Linux.deb

RUN useradd -ms /bin/bash uMetadata
USER uMetadata
WORKDIR /home/uMetadata
